apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: backend
  namespace: flux-system
spec:
  image: asia.gcr.io/xthanos/python-check-ip
  interval: 30s
  secretRef:
    name: gcr-json-key
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: backend
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: '^\d{18}$'
  imageRepositoryRef:
    name: backend
  policy:
    numerical:
      order: asc
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: 
spec:
  chart:
    spec:
      chart: ./charts/microservices/backend
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m0s
  interval: 30s
  values:
    image:
      repository: "asia.gcr.io/xthanos/python-check-ip" # {"$imagepolicy": "flux-system:backend:name"}
      tag: "20230519132346" # {"$imagepolicy": "flux-system:backend:tag"}
    replicaCount: 1