apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  interval: 1h
  releaseName: mysql
  chart:
    spec:
      chart: ./charts/mysql
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 6h
  values:
    auth:
      rootPassword: "12345678"