apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-loadtester
  namespace: flagger-system
spec:
  interval: 1h
  releaseName: flagger-loadtester
  chart:
    spec:
      chart: ./charts/flagger-loadtester
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 6h
  values:
    image:
      repository: ghcr.io/fluxcd/flagger-loadtester
      tag: 0.28.1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi