apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress-nginx/ingress-nginx.yaml
- ingress-nginx/namespace.yaml
- flagger-system/namespace.yaml
- flagger-system/flagger.yaml
- flagger-system/flagger-loadtester.yaml

# App
- monolith.yaml
- nodejs-header-blocker.yaml

# Canary
- custom-resources

# Theo custom service
- flagger-gater.yaml
- slack-handler.yaml
- mysql/mysql.yaml