apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: monolith
  namespace: flux-system
spec:
  image: asia.gcr.io/xthanos/python-check-ip
  interval: 30s
  secretRef:
    name: gcr-json-key
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: monolith
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: monolith
  policy:
    numerical:
      order: asc
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monolith
  namespace: gitops-app
spec:
  chart:
    spec:
      chart: ./charts/monolith
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m0s
  interval: 30s
  values:
    image:
      repository: "asia.gcr.io/xthanos/python-check-ip" # {"$imagepolicy": "flux-system:monolith:name"}
      tag: "20230521092019" # {"$imagepolicy": "flux-system:monolith:tag"}
    # The canary replica count
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 1
    ingress:
      enabled: true
