apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nodejs-header-blocker
  namespace: flux-system
spec:
  image: asia.gcr.io/xthanos/nodejs-header-blocker
  interval: 30s
  secretRef:
    name: gcr-json-key
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nodejs-header-blocker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nodejs-header-blocker
  policy:
    numerical:
      order: asc
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodejs-header-blocker
  namespace: gitops-app
spec:
  chart:
    spec:
      chart: ./charts/nodejs-header-blocker
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m0s
  interval: 30s
  values:
    image:
      repository: "asia.gcr.io/xthanos/nodejs-header-blocker" # {"$imagepolicy": "flux-system:nodejs-header-blocker:name"}
      tag: "10000000000003" # {"$imagepolicy": "flux-system:nodejs-header-blocker:tag"}
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 1
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
        - host: nodejs-header-blocker.theojust.my.id
          http:
            paths:
              - backend:
                  service:
                    name: nodejs-header-blocker
                    port:
                      name: http
                path: /
                pathType: ImplementationSpecific
