apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: slack-handler
  namespace: flux-system
spec:
  image: asia.gcr.io/xthanos/slack-handler
  interval: 30s
  secretRef:
    name: gcr-json-key
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: slack-handler
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: slack-handler
  policy:
    numerical:
      order: asc
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: slack-handler
  namespace: gitops-app
spec:
  chart:
    spec:
      chart: ./charts/slack-handler
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m0s
  interval: 30s
  values:
    image:
      repository: "asia.gcr.io/xthanos/slack-handler" # {"$imagepolicy": "flux-system:slack-handler:name"}
      tag: "10000000000001" # {"$imagepolicy": "flux-system:slack-handler:tag"}
    replicaCount: 1
    ingress:
      enabled: false
